# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79efcb9c7a29b9272308f4a5013ae882b27dcd39288ad609f204b62cffe3eee087101847604dfcc13b94d88f0435d103e972974f00dfcaa46fa34640866088db

test:
  secret_key_base: 6fd2c33fcdd4bac9d7350024bca6e61fe99fa12c8444e5400f32acc482b5de42446ea53976fd0353a98b7d948565efa8d6992e410c34eea58ff6155df4e90300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
